--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET default_tablespace = '';

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';

CREATE TYPE public.order_status AS ENUM (
    'pending',
    'paid',
    'shipped'
);

CREATE FUNCTION public.touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  -- this comment has 'quotes' and a semicolon; inside a function
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    display_name text DEFAULT 'anonymous'::text,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    website character varying(200) DEFAULT 'http://x--y.example/a;b'::character varying,
    balance numeric(10,2) DEFAULT 0.00 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    public_id uuid DEFAULT gen_random_uuid() NOT NULL,
    legacy_id uuid DEFAULT public.uuid_generate_v4(),
    score double precision,
    is_admin boolean DEFAULT false NOT NULL,
    meta jsonb DEFAULT '{}'::jsonb,
    tags text[] DEFAULT ARRAY[]::text[]
);

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;

CREATE TABLE public.orders (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    status public.order_status DEFAULT 'pending'::public.order_status NOT NULL,
    total numeric(12,2) NOT NULL,
    note text
);

CREATE TABLE public.order_items (
    order_id bigint NOT NULL,
    line_no integer NOT NULL,
    sku character varying(64) NOT NULL,
    qty integer DEFAULT 1 NOT NULL,
    CONSTRAINT order_items_qty_check CHECK ((qty > 0))
);

CREATE TABLE public.profiles (
    id integer DEFAULT nextval('public.profiles_id_seq'::regclass) NOT NULL,
    user_id integer NOT NULL,
    bio text
);

CREATE TABLE audit.users (
    id integer NOT NULL,
    action text NOT NULL,
    actor_id integer
);

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);
ALTER TABLE ONLY public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

COPY public.users (id, email, display_name) FROM stdin;
1	a@example.com	Bob -- 'quoted
2	b@example.com	\N
\.

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (order_id, line_no);

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);

ALTER TABLE ONLY audit.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX idx_orders_user ON public.orders USING btree (user_id);
CREATE UNIQUE INDEX idx_order_items_sku ON public.order_items USING btree (sku);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY audit.users
    ADD CONSTRAINT users_actor_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id);

COMMENT ON TABLE public.users IS 'Application users';
COMMENT ON COLUMN public.users.email IS 'Login e-mail; it''s unique';

GRANT ALL ON SCHEMA public TO PUBLIC;

--
-- PostgreSQL database dump complete
--
