import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowRight, Bot, Download, Eye, GitCompare, HardDrive, Layers, Link2, Maximize2, Minimize2, ShieldCheck,
  Star, Upload,
} from 'lucide-react';
import { Footer } from '../components/layout/Footer';
import { PublicNav } from '../components/layout/PublicNav';
import { GitHubMark } from '../components/layout/GitHubMark';
import { SupportLink } from '../components/shared/SupportLink';
import Editor from './Editor';
import { REPO_URL } from '../config';
import { useGithubStars } from '../hooks/useGithubStars';
import { useReveal } from '../hooks/useReveal';
import { formatStars } from '../lib/githubStars';
import { importSQL } from '../utils/importers/sql';
import { exportSQL } from '../utils/exporters/sql';
import { exportPrisma } from '../utils/exporters/prisma';
import { exportDrizzle } from '../utils/exporters/drizzle';
import { exportDBML } from '../utils/exporters/dbml';
import './Home.css';

/* ── Real exporter output for the "one schema, every format" panel ───────────── */
const SAMPLE_SQL = `CREATE TABLE users (
  id uuid PRIMARY KEY,
  email text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE posts (
  id serial PRIMARY KEY,
  author_id uuid NOT NULL REFERENCES users(id),
  title text NOT NULL,
  published boolean DEFAULT false
);`;

type FormatId = 'prisma' | 'drizzle' | 'sql' | 'dbml';
const FORMATS: { id: FormatId; label: string; file: string }[] = [
  { id: 'prisma', label: 'Prisma', file: 'schema.prisma' },
  { id: 'drizzle', label: 'Drizzle', file: 'schema.ts' },
  { id: 'sql', label: 'SQL', file: 'schema.sql' },
  { id: 'dbml', label: 'DBML', file: 'schema.dbml' },
];

function useSampleExports(): Record<FormatId, string> {
  return useMemo(() => {
    const { tables, relationships } = importSQL(SAMPLE_SQL);
    const strip = (s: string) => s.replace(/^-- Generated by .*\n-- Dialect: .*\n-- .*\n\n/, '');
    return {
      prisma: exportPrisma(tables, relationships),
      drizzle: exportDrizzle(tables, relationships),
      sql: strip(exportSQL(tables, relationships, 'postgres')),
      dbml: exportDBML(tables, relationships),
    };
  }, []);
}

/* ── Small illustrative visuals for the feature cards (decorative) ───────────── */
function CanvasVisual() {
  return (
    <svg className="bento__svg" viewBox="0 0 420 190" aria-hidden role="presentation">
      <defs>
        <linearGradient id="hv-line" x1="0" x2="1">
          <stop offset="0" stopColor="#b085ff" />
          <stop offset="1" stopColor="#00e5a0" />
        </linearGradient>
      </defs>
      <path d="M118 62 C 170 62, 160 126, 214 126" fill="none" stroke="url(#hv-line)" strokeWidth="1.6" opacity=".85" />
      <path d="M118 78 C 150 78, 270 40, 306 40" fill="none" stroke="url(#hv-line)" strokeWidth="1.6" opacity=".55" />
      {[
        { x: 20, y: 30, name: 'users', rows: ['id', 'email', 'name'], c: '#4aa3ff' },
        { x: 214, y: 90, name: 'orders', rows: ['id', 'user_id', 'total'], c: '#ff7a59' },
        { x: 306, y: 10, name: 'products', rows: ['id', 'name', 'price'], c: '#2ecb8f' },
      ].map((t) => (
        <g key={t.name} transform={`translate(${t.x} ${t.y})`}>
          <rect width="98" height="76" rx="7" fill="#0f0f17" stroke="#2a2a40" />
          <rect width="98" height="20" rx="7" fill="#161622" />
          <rect y="14" width="98" height="6" fill="#161622" />
          <rect width="3" height="76" rx="1.5" fill={t.c} />
          <text x="12" y="14" fill="#ecebf5" fontSize="9.5" fontFamily="monospace" fontWeight="700">{t.name}</text>
          {t.rows.map((r, i) => (
            <text key={r} x="12" y={36 + i * 16} fill="#a6a5ba" fontSize="9" fontFamily="monospace">{r}</text>
          ))}
        </g>
      ))}
    </svg>
  );
}

/* ── Hero video (only shown if the file exists and can play) ─────────────────── */
function HeroVideo() {
  // Stay hidden until the browser has really loaded a frame, so a missing or broken file never
  // leaves an empty black box on the page.
  const [ready, setReady] = useState(false);
  return (
    <section className={`hv reveal${ready ? '' : ' hv--hidden'}`} aria-label="Product video" hidden={!ready}>
      <div className="hv__frame">
        <video
          className="hv__video"
          src="/media/hero.mp4"
          poster="/media/hero-poster.jpg"
          autoPlay
          muted
          loop
          playsInline
          preload="metadata"
          onLoadedData={() => setReady(true)}
        />
      </div>
    </section>
  );
}

const FAQ = [
  {
    q: 'Is Modellr really free?',
    a: 'Yes. It is MIT-licensed open-source software with no paid plan, no ads and no account. If it saved you time you can optionally buy the author a coffee; that unlocks nothing.',
  },
  {
    q: 'Where are my schemas stored?',
    a: 'Only in your browser (IndexedDB). Nothing is uploaded to a server. Clearing your browser data deletes them, so use Backup in the dashboard to keep a JSON copy.',
  },
  {
    q: 'Does it connect to my database?',
    a: 'No. You paste or upload a SQL dump (PostgreSQL, MySQL, SQLite, SQL Server syntax) or a Prisma schema, or start from a template. That is also why it can promise your data never leaves your device.',
  },
  {
    q: 'What can I export?',
    a: 'SQL for PostgreSQL, MySQL, SQLite and SQL Server, plus Prisma, Drizzle ORM, DBML, JSON, PNG and SVG. Always read generated SQL and migrations before running them on a real database.',
  },
  {
    q: 'How does the AI assistant work?',
    a: 'It is optional and bring-your-own-key. You give Modellr an OpenAI-compatible endpoint (OpenAI, OpenRouter, or a local model such as Ollama). Requests go straight from your browser to that provider; there is no AI hosted by Modellr.',
  },
  {
    q: 'How big a schema can it handle?',
    a: 'Editing stays smooth up to a few hundred tables, and viewing or light edits work at around a thousand. The measurements and limits are published in the repository.',
  },
  {
    q: 'Can I self-host it?',
    a: 'Yes. It is a static web app: build it with npm run build and serve the dist folder from any static host.',
  },
];

export default function Home() {
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [format, setFormat] = useState<FormatId>('prisma');
  const exports = useSampleExports();
  const stars = useGithubStars();
  useReveal();

  const active = FORMATS.find((f) => f.id === format)!;
  const starLabel = stars !== null ? formatStars(stars) : '';

  return (
    <div className="home site-main">
      <PublicNav />

      {/* ── Hero ─────────────────────────────────────────────── */}
      <header className="hero">
        <div className="hero__grid" aria-hidden />
        <div className="hero__glow hero__glow--a" aria-hidden />
        <div className="hero__glow hero__glow--b" aria-hidden />

        <div className="hero__inner">
          <a className="hero__badge" href={REPO_URL} target="_blank" rel="noopener noreferrer">
            <span className="hero__badge-dot" aria-hidden />
            Free and open source · MIT
            <ArrowRight size={14} aria-hidden />
          </a>

          <h1 className="hero__title">
            Design database schemas <span className="hero__title-em">in your browser.</span>
          </h1>
          <p className="hero__sub">
            Draw tables, import the SQL or Prisma you already have, and export SQL, Prisma, Drizzle or DBML.
            No sign-up, and your schemas never leave your device.
          </p>

          <div className="hero__cta">
            <Link to="/app" className="site-btn site-btn--accent site-btn--lg">
              Open the editor <ArrowRight size={16} aria-hidden />
            </Link>
            <a className="site-btn site-btn--outline site-btn--lg" href={REPO_URL} target="_blank" rel="noopener noreferrer">
              <GitHubMark size={16} />
              Star on GitHub
              {starLabel && (
                <span className="hero__stars">
                  <Star size={13} fill="currentColor" strokeWidth={0} aria-hidden />
                  {starLabel}
                </span>
              )}
            </a>
          </div>

          <ul className="hero__facts" aria-label="Highlights">
            <li><ShieldCheck size={15} aria-hidden /> Nothing uploaded</li>
            <li><Layers size={15} aria-hidden /> No account</li>
            <li><Download size={15} aria-hidden /> 7 export formats</li>
            <li><GitCompare size={15} aria-hidden /> Snapshots and diff</li>
          </ul>
        </div>

        {/* Live editor (desktop). Phones get the video / a link instead: the editor needs room. */}
        <div className="hero__stage reveal">
          <div className={`stage${isFullscreen ? ' stage--full' : ''}`}>
            <div className="stage__bar">
              <span className="stage__dots" aria-hidden><i /><i /><i /></span>
              <span className="stage__label"><Eye size={13} aria-hidden /> Live sandbox: try editing. Starts from the e-commerce template; edits here are not saved.</span>
              <button
                className="stage__full"
                onClick={() => setIsFullscreen((f) => !f)}
                aria-label={isFullscreen ? 'Exit fullscreen' : 'Fullscreen'}
                title={isFullscreen ? 'Exit fullscreen' : 'Fullscreen'}
              >
                {isFullscreen ? <Minimize2 size={15} /> : <Maximize2 size={15} />}
              </button>
            </div>
            <div className="stage__body">
              <Editor isSandbox />
            </div>
          </div>
          <div className="hero__mobile-note">
            <p>The full editor needs a bigger screen. Open it on a laptop or desktop to try it.</p>
            <Link to="/app" className="site-btn site-btn--brand">Open the editor</Link>
          </div>
        </div>
      </header>

      <HeroVideo />

      {/* ── Feature bento ────────────────────────────────────── */}
      <section className="sec" id="features">
        <div className="sec__inner">
          <p className="eyebrow reveal">What you get</p>
          <h2 className="sec__title reveal">Everything for the schema, nothing you have to sign up for.</h2>

          <div className="bento">
            <article className="bento__card bento__card--wide reveal">
              <div className="bento__text">
                <span className="bento__icon"><Layers size={18} aria-hidden /></span>
                <h3>A visual canvas that stays fast</h3>
                <p>
                  Tables, typed fields, drag-to-connect relationships, notes and groups, auto-layout, search and
                  undo. Smooth up to a few hundred tables.
                </p>
              </div>
              <CanvasVisual />
            </article>

            <article className="bento__card reveal" style={{ ['--reveal-delay' as string]: '60ms' }}>
              <span className="bento__icon"><Upload size={18} aria-hidden /></span>
              <h3>Import what you have</h3>
              <p>Paste a SQL dump or a Prisma schema. pg_dump and mysqldump files work, foreign keys included.</p>
              <div className="bento__chips"><span>PostgreSQL</span><span>MySQL</span><span>SQLite</span><span>SQL Server</span><span>Prisma</span></div>
            </article>

            <article className="bento__card reveal" style={{ ['--reveal-delay' as string]: '120ms' }}>
              <span className="bento__icon"><GitCompare size={18} aria-hidden /></span>
              <h3>Snapshots and diff</h3>
              <p>Save versions, compare with any snapshot and generate migration SQL to review.</p>
              <div className="bento__diff" aria-hidden>
                <div className="d-add">+ ALTER TABLE "posts" ADD COLUMN "slug" text;</div>
                <div className="d-add">+ CREATE TABLE "tags" (...);</div>
                <div className="d-del">- DROP COLUMN "legacy_id";</div>
              </div>
            </article>

            <article className="bento__card reveal" style={{ ['--reveal-delay' as string]: '60ms' }}>
              <span className="bento__icon"><Link2 size={18} aria-hidden /></span>
              <h3>Share without a server</h3>
              <p>The schema is compressed into the link. Anyone with it gets a read-only snapshot, or an iframe embed.</p>
              <div className="bento__url" aria-hidden>/app/shared#/schema/N4IgLgh…</div>
            </article>

            <article className="bento__card reveal" style={{ ['--reveal-delay' as string]: '120ms' }}>
              <span className="bento__icon"><HardDrive size={18} aria-hidden /></span>
              <h3>Local-first</h3>
              <p>Projects live in your browser's IndexedDB. Back up everything as one JSON file whenever you like.</p>
              <div className="bento__chips"><span>IndexedDB</span><span>JSON backup</span><span>No account</span></div>
            </article>

            <article className="bento__card bento__card--full reveal" style={{ ['--reveal-delay' as string]: '180ms' }}>
              <div className="bento__text">
                <span className="bento__icon"><Bot size={18} aria-hidden /></span>
                <h3>Optional AI, with your own key</h3>
                <p>Describe a change in plain English and review the proposal before it touches your schema. Requests go straight from your browser to the provider you choose, including a local model.</p>
              </div>
              <div className="bento__chat" aria-hidden>
                <div className="bento__bubble bento__bubble--you">add a comments table linked to users</div>
                <div className="bento__bubble bento__bubble--ai">Proposal: add table <b>comments</b> (id, body, created_at) and relate <b>comments.user_id</b> to <b>users.id</b>. <span>Accept · Reject</span></div>
                <div className="bento__chips"><span>OpenAI</span><span>OpenRouter</span><span>Ollama (local)</span></div>
              </div>
            </article>
          </div>
        </div>
      </section>

      {/* ── One schema, every format (real exporter output) ──── */}
      <section className="sec sec--alt" id="formats">
        <div className="sec__inner">
          <p className="eyebrow reveal">One schema, every format</p>
          <h2 className="sec__title reveal">Paste SQL. Get Prisma, Drizzle, SQL or DBML.</h2>
          <p className="sec__lead reveal">
            The panel on the right is real output from Modellr's exporters, generated live in your browser from the SQL on the left.
          </p>

          <div className="fmt reveal">
            <div className="fmt__pane">
              <div className="fmt__head"><span>schema.sql</span><span className="fmt__tag">input</span></div>
              <pre className="fmt__code" tabIndex={0}><code>{SAMPLE_SQL}</code></pre>
            </div>
            <div className="fmt__arrow" aria-hidden><ArrowRight size={20} /></div>
            <div className="fmt__pane">
              <div className="fmt__head">
                <div className="fmt__tabs" role="tablist" aria-label="Export format">
                  {FORMATS.map((f) => (
                    <button
                      key={f.id}
                      role="tab"
                      aria-selected={f.id === format}
                      className={`fmt__tab${f.id === format ? ' is-active' : ''}`}
                      onClick={() => setFormat(f.id)}
                    >
                      {f.label}
                    </button>
                  ))}
                </div>
                <span className="fmt__tag">{active.file}</span>
              </div>
              <pre className="fmt__code" tabIndex={0} role="tabpanel"><code>{exports[format]}</code></pre>
            </div>
          </div>
        </div>
      </section>

      {/* ── How it works ─────────────────────────────────────── */}
      <section className="sec" id="how">
        <div className="sec__inner">
          <p className="eyebrow reveal">How it works</p>
          <h2 className="sec__title reveal">From a dump to a diagram in three steps.</h2>
          <ol className="steps">
            {[
              { n: '01', t: 'Bring your schema', d: 'Paste SQL or a Prisma schema, start from a template, or draw tables from scratch.' },
              { n: '02', t: 'Refine on the canvas', d: 'Connect relationships, tidy with auto-layout, add notes, save snapshots as you go.' },
              { n: '03', t: 'Export or share', d: 'Copy SQL, Prisma, Drizzle or DBML, save PNG/SVG, or send a read-only link.' },
            ].map((s, i) => (
              <li key={s.n} className="steps__item reveal" style={{ ['--reveal-delay' as string]: `${i * 90}ms` }}>
                <span className="steps__n">{s.n}</span>
                <h3>{s.t}</h3>
                <p>{s.d}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* ── FAQ ──────────────────────────────────────────────── */}
      <section className="sec sec--alt" id="faq">
        <div className="sec__inner sec__inner--narrow">
          <p className="eyebrow reveal">FAQ</p>
          <h2 className="sec__title reveal">Questions, answered plainly.</h2>
          <div className="faq reveal">
            {FAQ.map((f) => (
              <details key={f.q} className="faq__item">
                <summary>{f.q}</summary>
                <p>{f.a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* ── Final CTA ────────────────────────────────────────── */}
      <section className="cta">
        <div className="cta__glow" aria-hidden />
        <div className="cta__inner reveal">
          <h2>Start designing. It's free.</h2>
          <p>Open source under the MIT license. No sign-up, no install.</p>
          <div className="cta__buttons">
            <Link to="/app" className="site-btn site-btn--accent site-btn--lg">Open the editor <ArrowRight size={16} aria-hidden /></Link>
            <a className="site-btn site-btn--outline site-btn--lg" href={REPO_URL} target="_blank" rel="noopener noreferrer">
              <GitHubMark size={16} /> Star on GitHub
            </a>
          </div>
          <SupportLink className="cta__support" />
        </div>
      </section>

      <Footer />
    </div>
  );
}
