import { Suspense, lazy, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { SiteShell } from '../components/site/SiteShell';
import { ArtBars, ArtCubes, ArtStack } from '../components/site/Art';
import { MiniSchema } from '../components/site/MiniSchema';
import { GitHubMark } from '../components/layout/GitHubMark';
import { REPO_URL } from '../config';
import { useGithubStars } from '../hooks/useGithubStars';
import { formatStars } from '../lib/githubStars';
import { Highlighted, type CodeLang } from '../lib/highlight';
import { useUIStore } from '../store/ui';
import { TEMPLATES } from '../utils/templates';
import { importSQL } from '../utils/importers/sql';
import { exportSQL } from '../utils/exporters/sql';
import { exportPrisma } from '../utils/exporters/prisma';
import { exportDrizzle } from '../utils/exporters/drizzle';
import { exportDBML } from '../utils/exporters/dbml';
import editorDark from '../assets/editor-dark.webp';
import editorLight from '../assets/editor-light.webp';

const Editor = lazy(() => import('./Editor'));

/* Real exporter output for the "import / export" panel. */
const SAMPLE_SQL = `CREATE TABLE users (
  id uuid PRIMARY KEY,
  email text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE posts (
  id serial PRIMARY KEY,
  author_id uuid NOT NULL REFERENCES users(id),
  title text NOT NULL
);`;

type FormatId = 'prisma' | 'drizzle' | 'sql' | 'dbml';
const FORMATS: { id: FormatId; label: string; file: string; lang: CodeLang }[] = [
  { id: 'prisma', label: 'Prisma', file: 'schema.prisma', lang: 'prisma' },
  { id: 'drizzle', label: 'Drizzle', file: 'schema.ts', lang: 'ts' },
  { id: 'sql', label: 'SQL', file: 'schema.sql', lang: 'sql' },
  { id: 'dbml', label: 'DBML', file: 'schema.dbml', lang: 'dbml' },
];

function useSampleExports(): Record<FormatId, string> {
  return useMemo(() => {
    const { tables, relationships } = importSQL(SAMPLE_SQL);
    const strip = (s: string) => s.replace(/^-- Generated by .*\n-- Dialect: .*\n-- .*\n\n/, '');
    return {
      prisma: exportPrisma(tables, relationships),
      drizzle: exportDrizzle(tables, relationships),
      sql: strip(exportSQL(tables, relationships, 'postgres')),
      dbml: exportDBML(tables, relationships),
    };
  }, []);
}

const FAQ = [
  ['Is Modellr really free?', 'Yes. It is MIT-licensed open-source software with no paid plan, no ads and no account. If it saved you time you can optionally buy the author a coffee; that unlocks nothing.'],
  ['Where are my schemas stored?', 'Only in your browser (IndexedDB). Nothing is uploaded to a server. Clearing your browser data deletes them, so use Backup in the dashboard to keep a JSON copy.'],
  ['Does it connect to my database?', 'No. You paste or upload a SQL dump (PostgreSQL, MySQL, SQLite, SQL Server syntax) or a Prisma schema, or start from a template. That is also why it can promise your data never leaves your device.'],
  ['What can I export?', 'SQL for PostgreSQL, MySQL, SQLite and SQL Server, plus Prisma, Drizzle ORM, DBML, JSON, PNG and SVG. Always read generated SQL and migrations before running them on a real database.'],
  ['How does the AI assistant work?', 'It is optional and bring-your-own-key. You give Modellr an OpenAI-compatible endpoint (OpenAI, OpenRouter, or a local model such as Ollama). Requests go straight from your browser to that provider; there is no AI hosted by Modellr.'],
  ['How big a schema can it handle?', 'Editing stays smooth up to a few hundred tables, and viewing or light edits work at around a thousand. The measurements and limits are published in the repository.'],
  ['Can I self-host it?', 'Yes. It is a static web app: build it with npm run build and serve the dist folder from any static host.'],
] as const;

const CHANGELOG = [
  { date: 'Oct 1, 2026', title: 'Free and local-first', body: 'Accounts, cloud sync and billing were removed. Everything runs in the browser under the MIT license.' },
  { date: 'Oct 1, 2026', title: 'New importers and exporters', body: 'SQL and Prisma importers were rewritten; SQL, Prisma, Drizzle and DBML exporters are covered by round-trip tests.' },
  { date: 'Oct 1, 2026', title: 'Bring-your-own-key AI', body: 'A browser-direct client for OpenAI-compatible endpoints, including local models.' },
  { date: 'Oct 1, 2026', title: 'Performance at 1,000 tables', body: 'Selector-based store, virtualised rendering and a layout worker keep large schemas responsive.' },
];

function Hero() {
  const theme = useUIStore((s) => s.theme);
  const [live, setLive] = useState(false);
  const img = theme === 'light' ? editorLight : editorDark;

  return (
    <section className="n-hero">
      <div className="n-dots" aria-hidden="true" />
      <div className="n-wrap">
        <div className="n-hero__grid">
          <div className="n-hero__copy">
            <span className="n-eyebrow">Free · open source · MIT</span>
            <h1 className="n-h1">The database designer that never leaves your browser.</h1>
            <p className="n-lead">Draw tables and relationships, import the SQL or Prisma you already have, and export what your stack needs. No account. Nothing uploaded.</p>
            <div className="n-hero__actions">
              <Link to="/app" className="n-btn n-btn--lg">Open the editor</Link>
              <a className="n-btn n-btn--secondary n-btn--lg" href={REPO_URL} target="_blank" rel="noopener noreferrer"><GitHubMark size={16} /> Star on GitHub</a>
            </div>
          </div>
          <ul className="n-hero__meta" aria-label="Highlights">
            <li>No sign-up, no server</li>
            <li>PostgreSQL · MySQL · SQLite · SQL Server</li>
            <li>SQL, Prisma, Drizzle, DBML, PNG, SVG</li>
            <li>Smooth at 1,000 tables</li>
          </ul>
        </div>

        <div className={`n-shot${live ? ' n-shot--open' : ''}`}>
          <div className="n-shot__glow" aria-hidden="true" />
          <div className="n-shot__frame">
            <div className="n-shot__bar">
              <span className="n-shot__dots" aria-hidden="true"><i /><i /><i /></span>
              <span>{live ? 'modellr / e-commerce: live sandbox, edits are not saved' : 'modellr / e-commerce template'}</span>
              <button type="button" className="n-btn n-btn--secondary n-btn--sm n-shot__live" onClick={() => setLive((v) => !v)}>
                {live ? 'Back to preview' : 'Try it live'}
              </button>
            </div>
            {live ? (
              <div className="n-live">
                <Suspense fallback={<div className="n-skeleton" style={{ position: 'absolute', inset: 0 }} />}>
                  <Editor isSandbox />
                </Suspense>
              </div>
            ) : (
              <div className="n-shot__stage">
                <img className="n-shot__img n-shot__img--wide" src={img} width={1800} height={1018} alt="The Modellr editor showing four linked tables: users, orders, products and order_items" />
                <svg className="n-shot__rings" viewBox="0 0 2000 1131" preserveAspectRatio="none" aria-hidden="true">
                  <g fill="none" stroke="var(--n-accent)" strokeWidth="3">
                    <circle cx="815" cy="299" r="26" /><circle cx="1322" cy="353" r="26" />
                    <path d="M752 168 L752 190 L800 280" /><path d="M1420 168 L1420 190 L1340 335" />
                  </g>
                </svg>
                <span className="n-callout" style={{ left: '27.5%', top: '9.5%' }}>Primary key</span>
                <span className="n-callout" style={{ left: '62%', top: '9.5%' }}>Foreign key: draws the line</span>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}

function Formats() {
  const exports = useSampleExports();
  const [format, setFormat] = useState<FormatId>('prisma');
  const active = FORMATS.find((f) => f.id === format)!;

  const onKey = (e: React.KeyboardEvent) => {
    const i = FORMATS.findIndex((f) => f.id === format);
    if (e.key === 'ArrowRight') setFormat(FORMATS[(i + 1) % FORMATS.length].id);
    else if (e.key === 'ArrowLeft') setFormat(FORMATS[(i + FORMATS.length - 1) % FORMATS.length].id);
    else return;
    e.preventDefault();
  };

  return (
    <div className="n-formats">
      <div className="n-panel">
        <div className="n-panel__head"><span>schema.sql</span><span>input</span></div>
        <pre className="n-code" tabIndex={0}><code><Highlighted code={SAMPLE_SQL} lang="sql" /></code></pre>
      </div>
      <div className="n-formats__arrow" aria-hidden="true">→</div>
      <div className="n-panel">
        <div className="n-panel__head">
          <div className="n-tabs" role="tablist" aria-label="Export format" onKeyDown={onKey}>
            {FORMATS.map((f) => (
              <button key={f.id} type="button" role="tab" id={`fmt-tab-${f.id}`} aria-selected={f.id === format} aria-controls="fmt-panel" tabIndex={f.id === format ? 0 : -1} className="n-tab" onClick={() => setFormat(f.id)}>
                {f.label}
              </button>
            ))}
          </div>
          <span>{active.file}</span>
        </div>
        <pre className="n-code" id="fmt-panel" role="tabpanel" aria-labelledby={`fmt-tab-${format}`} tabIndex={0}><code><Highlighted code={exports[format]} lang={active.lang} /></code></pre>
      </div>
    </div>
  );
}

export default function Home() {
  const stars = useGithubStars();
  const starLabel = stars !== null ? formatStars(stars) : '';
  const demo = TEMPLATES.ecommerce ?? Object.values(TEMPLATES)[0];
  const demoTables = demo.tables.slice(0, 3);

  return (
    <SiteShell route="/">
      <Hero />

      <section className="n-works" aria-label="Supported formats">
        <div className="n-wrap">
          <p className="n-works__label">Imports and exports the formats you already use</p>
          <div className="n-works__row">
            {['PostgreSQL', 'MySQL', 'SQLite', 'SQL Server', 'Prisma', 'Drizzle', 'DBML'].map((x) => <span key={x} className="n-works__item">{x}</span>)}
          </div>
        </div>
      </section>

      <section className="n-section">
        <div className="n-wrap">
          <p className="n-statement">
            A schema tool that stays out of your way.{' '}
            <span>Modellr runs entirely in your browser: your tables, relationships and snapshots live in IndexedDB on your machine. No account, no server, nothing to sync.</span>
          </p>
          <div className="n-trio">
            <div><div className="n-trio__art"><ArtStack /></div><h3 className="n-h4">Local-first by design</h3><p className="n-small">Projects are stored in your browser. Back everything up as one JSON file and restore it on any machine.</p></div>
            <div><div className="n-trio__art"><ArtCubes /></div><h3 className="n-h4">Real formats, tested</h3><p className="n-small">Importers and exporters are covered by round-trip tests, so what you paste in is what comes back out.</p></div>
            <div><div className="n-trio__art"><ArtBars /></div><h3 className="n-h4">Built for big schemas</h3><p className="n-small">Virtualised canvas and a layout worker keep dragging near 60 fps at a thousand tables.</p></div>
          </div>
        </div>
      </section>

      <section className="n-section n-section--tight">
        <div className="n-wrap">
          <div className="n-feature__head">
            <h2 className="n-h2">Import what you have.<br />Export what you ship.</h2>
            <div className="n-feature__copy">
              <p className="n-lead" style={{ fontSize: '1rem' }}>Paste a <code className="n-mono">pg_dump</code>, a <code className="n-mono">mysqldump</code> or a Prisma schema and get a diagram. Change it on the canvas, then copy SQL, Prisma, Drizzle or DBML. The output on the right is generated live by the real exporters.</p>
              <Link className="n-arrow" to="/docs">Read the import docs</Link>
            </div>
          </div>
          <Formats />
        </div>
      </section>

      <section className="n-section n-section--tight">
        <div className="n-wrap">
          <div className="n-feature__head">
            <h2 className="n-h2">Snapshots, diff<br />and share links.</h2>
            <div className="n-feature__copy">
              <p className="n-lead" style={{ fontSize: '1rem' }}>Save versions as you go, compare against any of them and generate migration SQL with destructive-change warnings. Share a read-only link that carries the whole schema in the URL.</p>
              <Link className="n-arrow" to="/features">See all features</Link>
            </div>
          </div>
          <div className="n-bento">
            <article className="n-card span-3">
              <div className="n-card__art"><MiniSchema tables={demoTables} label="Snapshot versions of the e-commerce schema" /></div>
              <h3 className="n-h4">Snapshots and diff</h3>
              <p className="n-small">Restore any version, or diff it against the current schema. Renames show as drop + add, so read migrations before running them.</p>
            </article>
            <article className="n-card span-3">
              <div className="n-card__art" style={{ padding: 20, minHeight: 190, alignContent: 'center' }}>
                <div className="n-panel" style={{ width: '100%' }}>
                  <div className="n-panel__head"><span>/app/shared#N4Ig3gzg…</span><span className="n-badge n-badge--ok">read-only</span></div>
                  <div style={{ padding: '14px 16px', fontFamily: 'var(--n-mono)', fontSize: '.75rem', color: '#8b929b' }}>schema in the URL · 0 bytes uploaded</div>
                </div>
              </div>
              <h3 className="n-h4">Stateless share links</h3>
              <p className="n-small">The schema is compressed into the URL. Nothing is uploaded; recipients get a read-only snapshot they can save as their own.</p>
            </article>
            <article className="n-card span-2"><span className="n-card__meta">AI · optional</span><h3 className="n-h4">Bring your own key</h3><p className="n-small">OpenAI, OpenRouter or a local Ollama, called straight from your browser.</p></article>
            <article className="n-card span-2"><span className="n-card__meta">Export</span><h3 className="n-h4">PNG and SVG for docs</h3><p className="n-small">Drop the diagram into a README or a design doc.</p></article>
            <article className="n-card span-2"><span className="n-card__meta"><kbd className="n-kbd">Ctrl</kbd> <kbd className="n-kbd">K</kbd></span><h3 className="n-h4">Command palette</h3><p className="n-small">Search tables, jump anywhere, run any action from the keyboard.</p></article>
          </div>
        </div>
      </section>

      <section className="n-section n-section--tight">
        <div className="n-wrap">
          <h2 className="n-h2">Changelog</h2>
          <div className="n-changelog">
            {CHANGELOG.map((c) => (
              <div key={c.title} className="n-changelog__item"><span className="n-card__meta">{c.date}</span><h3 className="n-h4">{c.title}</h3><p className="n-small">{c.body}</p></div>
            ))}
          </div>
          <div className="n-oss">
            <div><b>MIT</b><span className="n-small">License. Fork it, host it, change it.</span></div>
            <div><b>0</b><span className="n-small">Accounts, servers or trackers.</span></div>
            <div><b>{starLabel ? `★ ${starLabel}` : '★'}</b><span className="n-small"><a className="n-link" href={REPO_URL} target="_blank" rel="noopener noreferrer">Star it on GitHub</a></span></div>
          </div>
        </div>
      </section>

      <section className="n-section n-section--tight">
        <div className="n-wrap">
          <h2 className="n-h2">Questions, answered plainly.</h2>
          <div className="n-faq">
            {FAQ.map(([q, a], i) => (
              <details key={q} open={i === 0}><summary>{q}</summary><p>{a}</p></details>
            ))}
          </div>
        </div>
      </section>

      <section className="n-section n-cta">
        <div className="n-wrap n-center">
          <h2 className="n-h1">Draw it. Export it.<br />Keep it.</h2>
          <p className="n-lead">Free and open source. No sign-up, no install.</p>
          <div className="n-cta__actions">
            <Link to="/app" className="n-btn n-btn--lg">Open the editor</Link>
            <a className="n-btn n-btn--secondary n-btn--lg" href={REPO_URL} target="_blank" rel="noopener noreferrer"><GitHubMark size={16} /> Star on GitHub</a>
          </div>
        </div>
      </section>
    </SiteShell>
  );
}
