import { generatePostgresSQL } from './sqlExporter.js';

export function generateMigration(diff, newState) {
  let sql = `-- Migration generated by SchemaForge Migration tool\n`;
  sql += `-- Created At: ${new Date().toISOString()}\n\n`;

  // 1. New Tables
  if (diff.addedTables.length > 0) {
    sql += `-- [CREATE] Added tables\n`;
    sql += generatePostgresSQL(diff.addedTables, newState.relationships.filter(r => diff.addedTables.find(t => t.id === r.sourceTableId))) + '\n\n';
  }

  // 2. Modified Tables
  for (const table of diff.modifiedTables) {
    sql += `-- [ALTER] Table "${table.name}"\n`;
    
    // Add columns
    for (const f of table.addedFields) {
      const nullable = f.nullable ? '' : ' NOT NULL';
      const def = f.default ? ` DEFAULT ${f.default}` : '';
      sql += `ALTER TABLE "${table.name}" ADD COLUMN "${f.name}" ${f.type}${nullable}${def};\n`;
    }

    // Remove columns
    for (const f of table.removedFields) {
      sql += `ALTER TABLE "${table.name}" DROP COLUMN "${f.name}";\n`;
    }

    // Modify columns
    for (const mf of table.modifiedFields) {
      if (mf.changes.type) {
        sql += `ALTER TABLE "${table.name}" ALTER COLUMN "${mf.name}" TYPE ${mf.changes.type.to};\n`;
      }
      if (mf.changes.nullable) {
        if (mf.changes.nullable.to === false) {
          sql += `ALTER TABLE "${table.name}" ALTER COLUMN "${mf.name}" SET NOT NULL;\n`;
        } else {
          sql += `ALTER TABLE "${table.name}" ALTER COLUMN "${mf.name}" DROP NOT NULL;\n`;
        }
      }
      if (mf.changes.default) {
        if (mf.changes.default.to === null || mf.changes.default.to === '') {
          sql += `ALTER TABLE "${table.name}" ALTER COLUMN "${mf.name}" DROP DEFAULT;\n`;
        } else {
          sql += `ALTER TABLE "${table.name}" ALTER COLUMN "${mf.name}" SET DEFAULT ${mf.changes.default.to};\n`;
        }
      }
    }
    sql += '\n';
  }

  // 3. Removed Tables
  if (diff.removedTables.length > 0) {
    sql += `-- [DROP] Removed tables\n`;
    for (const t of diff.removedTables) {
      sql += `DROP TABLE "${t.name}" CASCADE;\n`;
    }
  }

  return sql;
}
