import { generatePostgresSQL } from './sqlExporter.js';
import { escapeIdentifier, escapeLiteral } from './security.js';

export function generateMigration(diff, newState) {
  let sql = `-- Migration generated by Modellr Migration tool\n`;
  sql += `-- Created At: ${new Date().toISOString()}\n\n`;

  // 1. New Tables
  if (diff.addedTables.length > 0) {
    sql += `-- [CREATE] Added tables\n`;
    sql += generatePostgresSQL(diff.addedTables, newState.relationships.filter(r => diff.addedTables.find(t => t.id === r.sourceTableId))) + '\n\n';
  }

  // 2. Modified Tables
  for (const table of diff.modifiedTables) {
    const safeTableName = escapeIdentifier(table.name);
    sql += `-- [ALTER] Table ${safeTableName}\n`;

    // Add columns
    for (const f of table.addedFields) {
      const nullable = f.nullable ? '' : ' NOT NULL';
      const def = f.default ? ` DEFAULT ${escapeLiteral(f.default)}` : '';
      sql += `ALTER TABLE ${safeTableName} ADD COLUMN ${escapeIdentifier(f.name)} ${escapeLiteral(f.type)}${nullable}${def};\n`;
    }

    // Remove columns
    for (const f of table.removedFields) {
      sql += `ALTER TABLE ${safeTableName} DROP COLUMN ${escapeIdentifier(f.name)};\n`;
    }

    // Modify columns
    for (const mf of table.modifiedFields) {
      const safeFieldName = escapeIdentifier(mf.name);
      if (mf.changes.type) {
        sql += `ALTER TABLE ${safeTableName} ALTER COLUMN ${safeFieldName} TYPE ${escapeLiteral(mf.changes.type.to)};\n`;
      }
      if (mf.changes.nullable) {
        if (mf.changes.nullable.to === false) {
          sql += `ALTER TABLE ${safeTableName} ALTER COLUMN ${safeFieldName} SET NOT NULL;\n`;
        } else {
          sql += `ALTER TABLE ${safeTableName} ALTER COLUMN ${safeFieldName} DROP NOT NULL;\n`;
        }
      }
      if (mf.changes.default) {
        if (mf.changes.default.to === null || mf.changes.default.to === '') {
          sql += `ALTER TABLE ${safeTableName} ALTER COLUMN ${safeFieldName} DROP DEFAULT;\n`;
        } else {
          sql += `ALTER TABLE ${safeTableName} ALTER COLUMN ${safeFieldName} SET DEFAULT ${escapeLiteral(mf.changes.default.to)};\n`;
        }
      }
    }
    sql += '\n';
  }

  // 3. Removed Tables
  if (diff.removedTables.length > 0) {
    sql += `-- [DROP] Removed tables\n`;
    for (const t of diff.removedTables) {
      sql += `DROP TABLE ${escapeIdentifier(t.name)} CASCADE;\n`;
    }
  }

  return sql;
}
