import { escapeIdentifier, escapeLiteral } from './security.js';

const NULLABLE = (nullable) => (nullable ? '' : ' NOT NULL');
const UNIQUE = (unique) => (unique ? ' UNIQUE' : '');
const DEFAULT = (def) => (def ? ` DEFAULT ${escapeLiteral(def)}` : '');
const CHECK = (check) => (check ? ` CHECK (${escapeLiteral(check)})` : '');

function fieldDDL(f) {
  const pk = f.isPK ? ' PRIMARY KEY' : '';
  return `  ${escapeIdentifier(f.name)} ${escapeLiteral(f.type)}${NULLABLE(f.nullable)}${UNIQUE(f.unique)}${DEFAULT(f.default)}${CHECK(f.check)}${pk}`;
}

export function generatePostgresSQL(tables, relationships) {
  const tableMap = new Map(tables.map((t) => [t.id, t]));
  const fieldMap = new Map(
    tables.flatMap((t) => t.fields.map((f) => [`${t.id}:${f.id}`, { table: t, field: f }]))
  );

  // 1. Create Tables without inline FKs to avoid circular dependency issues
  const createStatements = tables.map((table) => {
    const cols = table.fields.map(fieldDDL);
    return `CREATE TABLE ${escapeIdentifier(table.name)} (\n${cols.join(',\n')}\n);`;
  });

  // 2. Add FK constraints via ALTER TABLE
  const alterStatements = (relationships || [])
    .map((r) => {
      const sourceTable = tableMap.get(r.sourceTableId);
      const targetTable = tableMap.get(r.targetTableId);
      const sourceField = (fieldMap.get(`${r.sourceTableId}:${r.sourceFieldId}`) || {}).field;
      const targetField = (fieldMap.get(`${r.targetTableId}:${r.targetFieldId}`) || {}).field;
      
      if (!sourceTable || !targetTable || !sourceField || !targetField) return null;
      
      return `ALTER TABLE ${escapeIdentifier(sourceTable.name)} \n  ADD CONSTRAINT ${escapeIdentifier(`fk_${sourceTable.name}_${sourceField.name}`)} \n  FOREIGN KEY (${escapeIdentifier(sourceField.name)}) REFERENCES ${escapeIdentifier(targetTable.name)} (${escapeIdentifier(targetField.name)});`;
    })
    .filter(Boolean);

  const header = `-- Generated by Modellr MCP\n-- Dialect: postgres\n-- ${new Date().toISOString()}\n\n`;
  return header + createStatements.join('\n\n') + '\n\n' + alterStatements.join('\n\n');
}
