const NULLABLE = (nullable) => (nullable ? '' : ' NOT NULL');
const UNIQUE = (unique) => (unique ? ' UNIQUE' : '');
const DEFAULT = (def) => (def ? ` DEFAULT ${def}` : '');
const CHECK = (check) => (check ? ` CHECK (${check})` : '');

function fieldDDL(f) {
  const pk = f.isPK ? ' PRIMARY KEY' : '';
  return `  "${f.name}" ${f.type}${NULLABLE(f.nullable)}${UNIQUE(f.unique)}$ DEFAULT(f.default)}${CHECK(f.check)}${pk}`;
}

export function generatePostgresSQL(tables, relationships) {
  const tableMap = new Map(tables.map((t) => [t.id, t]));
  const fieldMap = new Map(
    tables.flatMap((t) => t.fields.map((f) => [`${t.id}:${f.id}`, { table: t, field: f }]))
  );

  const stmts = tables.map((table) => {
    const cols = table.fields.map(fieldDDL);

    // Add FK constraints
    const fks = (relationships || [])
      .filter((r) => r.sourceTableId === table.id)
      .map((r) => {
        const targetTable = tableMap.get(r.targetTableId);
        const sourceField = (fieldMap.get(`${r.sourceTableId}:${r.sourceFieldId}`) || {}).field;
        const targetField = (fieldMap.get(`${r.targetTableId}:${r.targetFieldId}`) || {}).field;
        if (!targetTable || !sourceField || !targetField) return null;
        return `  FOREIGN KEY ("${sourceField.name}") REFERENCES "${targetTable.name}" ("${targetField.name}")`;
      })
      .filter(Boolean);

    const allCols = [...cols, ...fks];
    return `CREATE TABLE "${table.name}" (\n${allCols.join(',\n')}\n);`;
  });

  const header = `-- Generated by SchemaForge MCP\n-- Dialect: postgres\n-- ${new Date().toISOString()}\n\n`;
  return header + stmts.join('\n\n');
}
