import type { Table, Relationship } from '../../types/schema';

export function exportDBML(tables: Table[], relationships: Relationship[]): string {
  const fieldMap = new Map(
    tables.flatMap((t) => t.fields.map((f) => [`${t.id}:${f.id}`, { table: t, field: f }]))
  );

  const tableStmts = tables.map((table) => {
    const fields = table.fields.map((f) => {
      const opts: string[] = [];
      if (f.isPK) opts.push('pk');
      if (!f.nullable) opts.push('not null');
      if (f.unique) opts.push('unique');
      if (f.default) opts.push(`default: \`${f.default}\``);
      if (f.comment) opts.push(`note: '${f.comment}'`);
      const optsStr = opts.length ? ` [${opts.join(', ')}]` : '';
      return `  ${f.name} ${f.type}${optsStr}`;
    });
    return `Table ${table.name} {\n${fields.join('\n')}\n}`;
  });

  const refStmts = relationships.map((r) => {
    const sourceField = fieldMap.get(`${r.sourceTableId}:${r.sourceFieldId}`);
    const targetField = fieldMap.get(`${r.targetTableId}:${r.targetFieldId}`);
    if (!sourceField || !targetField) return null;
    const arrow = r.cardinality === 'one-to-many' ? '>' : r.cardinality === 'many-to-many' ? '<>' : '-';
    return `Ref: ${sourceField.table.name}.${sourceField.field.name} ${arrow} ${targetField.table.name}.${targetField.field.name}`;
  }).filter(Boolean);

  const header = `// Generated by Modellr\n// ${new Date().toISOString()}\n\n`;
  return header + [...tableStmts, '', ...refStmts].join('\n');
}
