import type { Table, Relationship, Field } from '../../types/schema';

/** Generate Drizzle ORM TypeScript Definitions */
export function exportDrizzle(tables: Table[], relationships: Relationship[]): string {
  const lines: string[] = [];
  
  lines.push('// Generated by SchemaForge');
  lines.push('// https://schemaforge.dev');
  lines.push('');
  lines.push("import { pgTable, serial, integer, text, varchar, boolean, timestamp, numeric, jsonb, uuid, foreignKey, index } from 'drizzle-orm/pg-core';");
  lines.push("import { relations } from 'drizzle-orm';");
  lines.push('');

  // ── Tables ────────────────────────────────────────────────────────────────
  for (const table of tables) {
    const tableName = table.name;
    const constName = tableName.toLowerCase() + 'Table';
    
    lines.push(`export const ${constName} = pgTable('${tableName}', {`);
    
    for (const field of table.fields) {
      const fieldLine = buildDrizzleField(field);
      lines.push(`  ${field.name}: ${fieldLine},`);
    }
    
    lines.push('});');
    lines.push('');
  }

  // ── Relations ─────────────────────────────────────────────────────────────
  if (relationships.length > 0) {
    lines.push('/** Relations */');
    
    for (const table of tables) {
      const constName = table.name.toLowerCase() + 'Table';
      
      const outgoing = relationships.filter((r) => r.sourceTableId === table.id);
      const incoming = relationships.filter((r) => r.targetTableId === table.id);
      
      if (outgoing.length === 0 && incoming.length === 0) continue;
      
      lines.push(`export const ${constName}Relations = relations(${constName}, ({ one, many }) => ({`);
      
      // Belongs To (Many-to-One / One-to-One Outgoing)
      for (const rel of outgoing) {
        const targetTable = tables.find((t) => t.id === rel.targetTableId);
        if (!targetTable) continue;
        const targetConst = targetTable.name.toLowerCase() + 'Table';
        const fieldName = targetTable.name.toLowerCase();
        
        lines.push(`  ${fieldName}: one(${targetConst}, {`);
        lines.push(`    fields: [${constName}.${rel.sourceFieldId}],`); // sourceFieldId is the actual name string if matching DBML pattern, or UUID. Wait: SchemaForge ID vs Name!
        // Assuming we need the field name for sourceFieldId! Let's resolve it.
        const sf = table.fields.find(f => f.id === rel.sourceFieldId);
        const tf = targetTable.fields.find(f => f.id === rel.targetFieldId);
        if (sf && tf) {
          lines.push(`    fields: [${constName}.${sf.name}],`);
          lines.push(`    references: [${targetConst}.${tf.name}]`);
        }
        lines.push(`  }),`);
      }
      
      // Has Many
      for (const rel of incoming) {
        const sourceTable = tables.find((t) => t.id === rel.sourceTableId);
        if (!sourceTable) continue;
        const sourceConst = sourceTable.name.toLowerCase() + 'Table';
        const relName = sourceTable.name.toLowerCase() + (rel.cardinality === 'one-to-many' ? 's' : '');
        const method = rel.cardinality === 'one-to-many' ? 'many' : 'one';
        
        lines.push(`  ${relName}: ${method}(${sourceConst}),`);
      }
      
      lines.push('}));');
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ── Helpers ─────────────────────────────────────────────────────────────────



function buildDrizzleField(field: Field): string {
  const t = field.type.toLowerCase().trim();
  let base = 'text';
  let params = '';

  // Parse type
  if (['serial', 'serial4', 'int4', 'integer', 'int'].includes(t)) {
    // If it's a PK and INT, typically we use serial() or integer() based on auto-increment
    if (field.isPK) base = 'serial';
    else base = 'integer';
  }
  else if (['bigserial', 'serial8'].includes(t)) base = 'bigserial';
  else if (['bigint', 'int8'].includes(t)) { base = 'bigint'; params = `{ mode: 'number' }`; }
  else if (t.startsWith('varchar')) {
    const match = t.match(/\d+/);
    if (match) { base = 'varchar'; params = `{ length: ${match[0]} }`; }
    else base = 'varchar';
  }
  else if (['boolean', 'bool'].includes(t)) base = 'boolean';
  else if (['timestamp', 'timestamptz', 'datetime'].includes(t)) {
    base = 'timestamp';
    if (t.includes('tz')) params = `{ withTimezone: true }`;
  }
  else if (['decimal', 'numeric'].includes(t)) base = 'numeric';
  else if (['json', 'jsonb'].includes(t)) base = 'jsonb';
  else if (['uuid'].includes(t)) base = 'uuid';

  // Construct declaration
  let def = `${base}('${field.name}'${params ? ', ' + params : ''})`;
  if (field.isPK) def += '.primaryKey()';
  if (!field.nullable && !field.isPK) def += '.notNull()';
  if (field.unique && !field.isPK) def += '.unique()';
  
  if (field.default) {
    const d = field.default.toLowerCase().trim();
    if (d === 'now()' || d === 'current_timestamp') def += '.defaultNow()';
    else if (d === 'uuid_generate_v4()') def += '.defaultRandom()';
    else if (!isNaN(Number(d)) || d === 'true' || d === 'false') def += `.default(${d})`;
    else def += `.default('${field.default.replace(/'/g, '')}')`;
  }

  return def;
}
