import type { Table, Relationship } from '../../types/schema';

/** Generate a Prisma schema file from the current schema */
export function exportPrisma(
  tables: Table[],
  relationships: Relationship[],
  dbUrl = 'postgresql://USER:PASSWORD@localhost:5432/DB'
): string {
  const lines: string[] = [];

  lines.push('// Generated by SchemaForge');
  lines.push('// https://schemaforge.dev');
  lines.push('');
  lines.push('generator client {');
  lines.push('  provider = "prisma-client-js"');
  lines.push('}');
  lines.push('');
  lines.push('datasource db {');
  lines.push('  provider = "postgresql"');
  lines.push(`  url      = env("DATABASE_URL")`);
  lines.push('}');
  lines.push('');

  // Build FK lookup: fieldId → target table name
  const fkTargetMap = new Map<string, string>();
  for (const rel of relationships) {
    const targetTable = tables.find((t) => t.id === rel.targetTableId);
    if (targetTable) {
      fkTargetMap.set(rel.sourceFieldId, targetTable.name);
    }
  }

  for (const table of tables) {
    const modelName = toPascalCase(table.name);
    lines.push(`model ${modelName} {`);

    for (const field of table.fields) {
      const prismaType = toPrismaType(field.type);
      const isFK = field.isFK && fkTargetMap.has(field.id);
      const targetTableName = isFK ? fkTargetMap.get(field.id)! : null;
      const targetModel = targetTableName ? toPascalCase(targetTableName) : null;

      const attrs: string[] = [];
      if (field.isPK) attrs.push('@id');
      if (field.unique && !field.isPK) attrs.push('@unique');

      if (isPrismaAutoType(field.type)) {
        attrs.push('@default(autoincrement())');
      } else if (field.type === 'uuid') {
        attrs.push('@default(uuid())');
      } else if (field.default) {
        const def = formatPrismaDefault(field.default);
        if (def) attrs.push(`@default(${def})`);
      }

      const optionalMark = field.nullable ? '?' : '';
      const attrStr = attrs.length ? '  ' + attrs.join(' ') : '';

      lines.push(`  ${field.name.padEnd(20)} ${prismaType}${optionalMark}${attrStr}`);

      // Add relation field for FKs
      if (isFK && targetModel) {
        const relFieldName = targetTableName!.toLowerCase();
        lines.push(`  ${relFieldName.padEnd(20)} ${targetModel}    @relation(fields: [${field.name}], references: [id])`);
      }
    }

    // Add back-relations
    const incomingRels = relationships.filter((r) => r.targetTableId === table.id);
    for (const rel of incomingRels) {
      const srcTable = tables.find((t) => t.id === rel.sourceTableId);
      if (!srcTable) continue;
      const srcModel = toPascalCase(srcTable.name);
      const isMany = rel.cardinality === 'one-to-many';
      const backFieldName = srcTable.name.toLowerCase() + (isMany ? 's' : '');
      const backType = isMany ? `${srcModel}[]` : `${srcModel}?`;
      lines.push(`  ${backFieldName.padEnd(20)} ${backType}`);
    }

    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

// ── Helpers ────────────────────────────────────────

function toPascalCase(name: string): string {
  return name
    .split(/[_\s-]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

function toPrismaType(sqlType: string): string {
  const t = sqlType.toLowerCase().trim();
  // Integer-like
  if (['int', 'integer', 'int4'].includes(t)) return 'Int';
  if (['bigint', 'int8', 'bigserial', 'serial8'].includes(t)) return 'BigInt';
  if (['smallint', 'int2'].includes(t)) return 'Int';
  if (['serial', 'serial4'].includes(t)) return 'Int';
  if (['tinyint'].includes(t)) return 'Int';
  // Float
  if (['real', 'float4', 'float'].includes(t)) return 'Float';
  if (['double precision', 'float8', 'double'].includes(t)) return 'Float';
  if (['decimal', 'numeric', 'money'].includes(t)) return 'Decimal';
  // String
  if (t.startsWith('varchar') || t.startsWith('nvarchar') || t.startsWith('char')) return 'String';
  if (['text', 'ntext', 'longtext', 'mediumtext', 'tinytext', 'clob'].includes(t)) return 'String';
  if (['citext', 'name'].includes(t)) return 'String';
  // Boolean
  if (['boolean', 'bool', 'bit'].includes(t)) return 'Boolean';
  // DateTime
  if (['timestamp', 'timestamptz', 'datetime', 'datetime2'].includes(t)) return 'DateTime';
  if (['date'].includes(t)) return 'DateTime';
  if (['time', 'timetz'].includes(t)) return 'String';
  // UUID
  if (['uuid', 'uniqueidentifier'].includes(t)) return 'String';
  // JSON
  if (['json', 'jsonb'].includes(t)) return 'Json';
  // Bytes
  if (['bytea', 'binary', 'varbinary', 'blob', 'image'].includes(t)) return 'Bytes';
  // Fallback
  return 'String';
}

function isPrismaAutoType(sqlType: string): boolean {
  const t = sqlType.toLowerCase();
  return ['serial', 'bigserial', 'smallserial', 'serial4', 'serial8'].includes(t) ||
    ['int', 'integer', 'bigint', 'smallint'].some((s) => t === s + ' generated always as identity');
}

function formatPrismaDefault(def: string): string {
  const d = def.trim().toLowerCase();
  if (d === 'now()' || d === 'current_timestamp') return 'now()';
  if (d === 'true' || d === 'false') return d;
  if (d === 'null') return '';
  if (!isNaN(Number(d))) return d;
  // String literal
  if (def.startsWith("'") && def.endsWith("'")) return `"${def.slice(1, -1)}"`;
  return `"${def}"`;
}
