import type { Table, Relationship, Field } from '../../types/schema';
import {
  analyzeDefault,
  commentText,
  parseType,
  resolveRelationships,
  stripControl,
  type DefaultInfo,
  type ParsedType,
} from './sqlUtils';
import { buildRelationNames, toIdentifier, toPascalCase, uniqueIdent } from './namingUtils';

/**
 * Generate a Prisma schema (PostgreSQL provider).
 *
 * Naming approach (consistent, Prisma-valid):
 *  - model name = PascalCase(table name); `@@map("table_name")` is added when
 *    the model name differs from the table name (almost always).
 *  - field names keep the database column names as-is (snake_case is legal in
 *    Prisma); `@map("column")` is only added when the column name is not a
 *    valid Prisma identifier.
 *  - every relation is a named relation (`@relation("posts_author_id", ...)`)
 *    with unique back-relation field names.
 */
export function exportPrisma(
  tables: Table[],
  relationships: Relationship[]
): string {
  const lines: string[] = [];
  lines.push('// Generated by Modellr');
  lines.push('');
  lines.push('generator client {');
  lines.push('  provider = "prisma-client-js"');
  lines.push('}');
  lines.push('');
  lines.push('datasource db {');
  lines.push('  provider = "postgresql"');
  lines.push(`  url      = env("DATABASE_URL")`);
  lines.push('}');
  lines.push('');

  const resolved = resolveRelationships(tables, relationships);

  // Model + field names
  const usedModels = new Set<string>();
  const modelName = new Map<string, string>();
  for (const t of tables) modelName.set(t.id, uniqueIdent(toPascalCase(t.name), usedModels));

  const fieldName = new Map<string, string>(); // `${tableId}:${fieldId}` -> prisma field name
  const byObject = new Map<Field, string>();
  for (const t of tables) {
    const used = new Set<string>();
    for (const f of t.fields) {
      const n = uniqueIdent(prismaFieldName(f.name), used);
      fieldName.set(`${t.id}:${f.id}`, n);
      byObject.set(f, n);
    }
  }

  // Relation field names never collide with scalar field names.
  const names = buildRelationNames(resolved, (f) => byObject.get(f) ?? f.name);

  for (const table of tables) {
    const model = modelName.get(table.id)!;
    const tableComment = commentText(table.comment);
    if (tableComment) lines.push(`/// ${tableComment}`);
    lines.push(`model ${model} {`);

    const pkFields = table.fields.filter((f) => f.isPK);
    const compositePk = pkFields.length > 1;

    interface Row { name: string; type: string; attrs: string[]; doc?: string }
    const rows: Row[] = [];

    for (const field of table.fields) {
      const pName = fieldName.get(`${table.id}:${field.id}`)!;
      const parsed = parseType(field.type);
      const pType = toPrismaType(parsed, field);
      const attrs: string[] = [];

      const isSinglePk = field.isPK && !compositePk;
      if (isSinglePk) attrs.push('@id');

      const def = prismaDefault(field, pType, parsed, isSinglePk);
      if (def) attrs.push(def);

      const fkRel = resolved.find((r) => r.sourceTable.id === table.id && r.sourceField.id === field.id);
      const needsUnique = field.unique || (fkRel ? names.get(fkRel)!.oneToOne : false);
      if (needsUnique && !field.isPK) attrs.push('@unique');
      if (pType.native) attrs.push(pType.native);
      if (pName !== field.name) attrs.push(`@map(${JSON.stringify(stripControl(field.name))})`);

      const optional = field.nullable && !field.isPK;
      rows.push({
        name: pName,
        type: `${pType.type}${pType.list ? '[]' : optional ? '?' : ''}`,
        attrs,
        doc: commentText(field.comment) || undefined,
      });
    }

    // Relation fields (forward side)
    for (const r of resolved.filter((x) => x.sourceTable.id === table.id)) {
      const n = names.get(r)!;
      const fk = fieldName.get(`${r.sourceTable.id}:${r.sourceField.id}`)!;
      const target = fieldName.get(`${r.targetTable.id}:${r.targetField.id}`)!;
      const optional = r.sourceField.nullable && !r.sourceField.isPK;
      rows.push({
        name: n.forward,
        type: `${modelName.get(r.targetTable.id)}${optional ? '?' : ''}`,
        attrs: [`@relation(${JSON.stringify(n.relationName)}, fields: [${fk}], references: [${target}])`],
      });
    }

    // Back-relation fields
    for (const r of resolved.filter((x) => x.targetTable.id === table.id)) {
      const n = names.get(r)!;
      const src = modelName.get(r.sourceTable.id)!;
      rows.push({
        name: n.back,
        type: n.oneToOne ? `${src}?` : `${src}[]`,
        attrs: [`@relation(${JSON.stringify(n.relationName)})`],
      });
    }

    const nameW = Math.max(0, ...rows.map((r) => r.name.length));
    const typeW = Math.max(0, ...rows.map((r) => r.type.length));
    for (const row of rows) {
      if (row.doc) lines.push(`  /// ${row.doc}`);
      const attrStr = row.attrs.length ? ` ${row.attrs.join(' ')}` : '';
      lines.push(`  ${row.name.padEnd(nameW)} ${row.type.padEnd(attrStr ? typeW : 0)}${attrStr}`.trimEnd());
    }

    const blockAttrs: string[] = [];
    if (compositePk) {
      blockAttrs.push(`@@id([${pkFields.map((f) => fieldName.get(`${table.id}:${f.id}`)!).join(', ')}])`);
    } else if (pkFields.length === 0 && !table.fields.some((f) => f.unique)) {
      blockAttrs.push('// WARNING: Prisma requires a unique identifier (@id / @@id / @unique) on every model');
    }
    if (model !== table.name) {
      blockAttrs.push(`@@map(${JSON.stringify(stripControl(table.name))})`);
    }
    if (blockAttrs.length) {
      lines.push('');
      for (const a of blockAttrs) lines.push(`  ${a}`);
    }

    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

// ── Helpers ────────────────────────────────────────

function prismaFieldName(name: string): string {
  let id = toIdentifier(name);
  if (!/^[A-Za-z]/.test(id)) id = `f${id}`;
  return id;
}

interface PrismaType {
  type: string;
  native?: string;
  list?: boolean;
  scalar: 'String' | 'Int' | 'BigInt' | 'Float' | 'Decimal' | 'Boolean' | 'DateTime' | 'Json' | 'Bytes' | 'Unsupported';
}

function num(args: string[], i: number): string | undefined {
  return args[i] && /^\d+$/.test(args[i]) ? args[i] : undefined;
}

function toPrismaType(p: ParsedType, field: Pick<Field, 'length' | 'precision' | 'scale'>): PrismaType {
  const list = p.arrayDims > 0;
  const mk = (scalar: PrismaType['scalar'], native?: string): PrismaType => ({
    type: scalar, scalar, native, list: list || undefined,
  });
  const len = num(p.args, 0) ?? (field.length && field.length > 0 ? String(Math.floor(field.length)) : undefined);
  switch (p.category) {
    case 'smallint': case 'tinyint': return mk('Int', '@db.SmallInt');
    case 'mediumint': case 'int': case 'serial': return mk('Int');
    case 'smallserial': return mk('Int', '@db.SmallInt');
    case 'bigint': case 'bigserial': return mk('BigInt');
    case 'real': return mk('Float', '@db.Real');
    case 'float': case 'double': return mk('Float');
    case 'decimal': {
      const precision = num(p.args, 0) ?? (field.precision ? String(Math.floor(field.precision)) : undefined);
      const scale = num(p.args, 1) ?? (field.scale != null && precision ? String(Math.floor(field.scale)) : undefined);
      return mk('Decimal', precision ? `@db.Decimal(${precision}${scale ? `, ${scale}` : ''})` : undefined);
    }
    case 'money': return mk('Decimal', '@db.Money');
    case 'char': return mk('String', `@db.Char(${len ?? 1})`);
    case 'varchar': return mk('String', len ? `@db.VarChar(${len})` : undefined);
    case 'text': return mk('String', p.base === 'citext' ? '@db.Citext' : undefined);
    case 'bool': case 'bit': return mk('Boolean');
    case 'timestamp': return mk('DateTime', `@db.Timestamp(${num(p.args, 0) ?? 6})`);
    case 'timestamptz': return mk('DateTime', `@db.Timestamptz(${num(p.args, 0) ?? 6})`);
    case 'date': return mk('DateTime', '@db.Date');
    case 'time':
      return mk('DateTime', `${p.base.includes('tz') || p.base.includes('with time') ? '@db.Timetz' : '@db.Time'}(${num(p.args, 0) ?? 6})`);
    case 'uuid': return mk('String', '@db.Uuid');
    case 'json': return mk('Json', p.base === 'json' ? '@db.Json' : undefined);
    case 'bytes': return mk('Bytes');
    default: {
      if (p.base === 'inet') return mk('String', '@db.Inet');
      if (p.base === 'xml') return mk('String', '@db.Xml');
      const unsupported = p.raw.replace(/\[\s*\d*\s*\]/g, '').replace(/["\\]/g, '');
      return { type: `Unsupported(${JSON.stringify(unsupported)})`, scalar: 'Unsupported', list: undefined };
    }
  }
}

function prismaDefault(field: Field, t: PrismaType, p: ParsedType, isSinglePk: boolean): string | undefined {
  const dbgen = (expr: string) => `@default(dbgenerated(${JSON.stringify(expr)}))`;
  const info: DefaultInfo | undefined = analyzeDefault(field.default);

  // Auto-increment types
  if (['serial', 'smallserial', 'bigserial'].includes(p.category)) return '@default(autoincrement())';
  if (t.list) {
    return info && info.kind !== 'null' && (info.kind === 'expr' || info.kind === 'string')
      ? dbgen(info.kind === 'expr' ? info.text : `'${(info as { value: string }).value.replace(/'/g, "''")}'`)
      : undefined;
  }

  if (!info) {
    // Primary-key uuid without an explicit default: generate client-side.
    if (p.category === 'uuid' && isSinglePk && !field.isFK) return '@default(uuid())';
    return undefined;
  }

  const numeric = t.scalar === 'Int' || t.scalar === 'BigInt' || t.scalar === 'Float' || t.scalar === 'Decimal';
  switch (info.kind) {
    case 'null':
      return undefined;
    case 'uuid':
      if (p.category === 'uuid' || t.scalar === 'String') return '@default(uuid())';
      return dbgen(info.text);
    case 'now':
      return t.scalar === 'DateTime' ? '@default(now())' : dbgen(info.text);
    case 'keyword':
      return dbgen(info.text);
    case 'bool':
      return t.scalar === 'Boolean' ? `@default(${info.value})` : dbgen(String(info.value));
    case 'number':
      if (t.scalar === 'Boolean' && (info.text === '0' || info.text === '1')) return `@default(${info.text === '1'})`;
      if (numeric) return `@default(${info.text})`;
      if (t.scalar === 'String') return `@default(${JSON.stringify(info.text)})`;
      return dbgen(info.text);
    case 'string': {
      if (t.scalar === 'String' || t.scalar === 'Json' || t.scalar === 'DateTime') {
        return `@default(${JSON.stringify(info.value)})`;
      }
      if (numeric && info.value.trim() !== '' && !isNaN(Number(info.value))) return `@default(${info.value.trim()})`;
      if (t.scalar === 'Boolean' && /^(true|false)$/i.test(info.value)) return `@default(${info.value.toLowerCase()})`;
      return dbgen(`'${info.value.replace(/'/g, "''")}'`);
    }
    case 'expr':
      if (/^nextval\(/i.test(info.text) && (t.scalar === 'Int' || t.scalar === 'BigInt')) return '@default(autoincrement())';
      return dbgen(info.text);
  }
}
