import type { Table, Relationship, Dialect } from '../../types/schema';

const NULLABLE = (nullable: boolean) => (nullable ? '' : ' NOT NULL');
const UNIQUE = (unique: boolean) => (unique ? ' UNIQUE' : '');
const DEFAULT = (def?: string) => (def ? ` DEFAULT ${def}` : '');
const CHECK = (check?: string) => (check ? ` CHECK (${check})` : '');

/**
 * Maps PostgreSQL-style types to MySQL-style types if needed
 */
function mapType(type: string, dialect: Dialect): string {
  if (dialect !== 'mysql') return type;
  const t = type.toLowerCase();
  if (t === 'uuid') return 'varchar(36)';
  if (t === 'bigserial') return 'BIGINT UNSIGNED NOT NULL AUTO_INCREMENT';
  if (t === 'serial') return 'INT UNSIGNED NOT NULL AUTO_INCREMENT';
  if (t === 'timestamptz') return 'timestamp';
  if (t === 'jsonb') return 'json';
  if (t === 'boolean') return 'tinyint(1)';
  return type;
}

function quote(name: string, dialect: Dialect): string {
  return dialect === 'mysql' ? `\`${name}\`` : `"${name}"`;
}

function fieldDDL(f: Table['fields'][0], dialect: Dialect): string {
  const mappedType = mapType(f.type, dialect);
  const pk = f.isPK ? ' PRIMARY KEY' : '';
  return `  ${quote(f.name, dialect)} ${mappedType}${NULLABLE(f.nullable)}${UNIQUE(f.unique)}${DEFAULT(f.default)}${CHECK(f.check)}${pk}`;
}

export function exportSQL(
  tables: Table[],
  relationships: Relationship[],
  dialect: Dialect
): string {
  const tableMap = new Map(tables.map((t) => [t.id, t]));
  const fieldMap = new Map(
    tables.flatMap((t) => t.fields.map((f) => [`${t.id}:${f.id}`, { table: t, field: f }]))
  );

  // 1. Create Tables (without FKs to avoid circular dependency issues)
  const createTableStmts = tables.map((table) => {
    const cols = table.fields.map(f => fieldDDL(f, dialect));
    return `CREATE TABLE ${quote(table.name, dialect)} (\n${cols.join(',\n')}\n);`;
  });

  // 2. Add Foreign Keys via ALTER TABLE
  const alterTableStmts: string[] = [];
  relationships.forEach((r) => {
    const sourceTable = tableMap.get(r.sourceTableId);
    const targetTable = tableMap.get(r.targetTableId);
    const sourceField = fieldMap.get(`${r.sourceTableId}:${r.sourceFieldId}`)?.field;
    const targetField = fieldMap.get(`${r.targetTableId}:${r.targetFieldId}`)?.field;

    if (sourceTable && targetTable && sourceField && targetField) {
      const fkName = `fk_${sourceTable.name}_${sourceField.name}`;
      alterTableStmts.push(
        `ALTER TABLE ${quote(sourceTable.name, dialect)} ADD CONSTRAINT ${quote(fkName, dialect)} FOREIGN KEY (${quote(sourceField.name, dialect)}) REFERENCES ${quote(targetTable.name, dialect)} (${quote(targetField.name, dialect)});`
      );
    }
  });

  const header = `-- Generated by SchemaForge\n-- Dialect: ${dialect}\n-- ${new Date().toISOString()}\n\n`;
  
  let result = header;
  result += createTableStmts.join('\n\n');
  if (alterTableStmts.length > 0) {
    result += '\n\n-- Foreign Keys\n';
    result += alterTableStmts.join('\n');
  }

  return result;
}
