import type { Table, Relationship, Dialect } from '../../types/schema';

const NULLABLE = (nullable: boolean) => (nullable ? '' : ' NOT NULL');
const UNIQUE = (unique: boolean) => (unique ? ' UNIQUE' : '');
const DEFAULT = (def?: string) => (def ? ` DEFAULT ${def}` : '');
const CHECK = (check?: string) => (check ? ` CHECK (${check})` : '');

function fieldDDL(f: Table['fields'][0]): string {
  const pk = f.isPK ? ' PRIMARY KEY' : '';
  return `  "${f.name}" ${f.type}${NULLABLE(f.nullable)}${UNIQUE(f.unique)}${DEFAULT(f.default)}${CHECK(f.check)}${pk}`;
}

export function exportSQL(
  tables: Table[],
  relationships: Relationship[],
  dialect: Dialect
): string {
  const tableMap = new Map(tables.map((t) => [t.id, t]));
  const fieldMap = new Map(
    tables.flatMap((t) => t.fields.map((f) => [`${t.id}:${f.id}`, { table: t, field: f }]))
  );

  const stmts = tables.map((table) => {
    const cols = table.fields.map(fieldDDL);

    // Add FK constraints
    const fks = relationships
      .filter((r) => r.sourceTableId === table.id)
      .map((r) => {
        const targetTable = tableMap.get(r.targetTableId);
        const sourceField = fieldMap.get(`${r.sourceTableId}:${r.sourceFieldId}`)?.field;
        const targetField = fieldMap.get(`${r.targetTableId}:${r.targetFieldId}`)?.field;
        if (!targetTable || !sourceField || !targetField) return null;
        return `  FOREIGN KEY ("${sourceField.name}") REFERENCES "${targetTable.name}" ("${targetField.name}")`;
      })
      .filter(Boolean);

    const allCols = [...cols, ...fks];
    return `CREATE TABLE "${table.name}" (\n${allCols.join(',\n')}\n);`;
  });

  const header = `-- Generated by SchemaForge\n-- Dialect: ${dialect}\n-- ${new Date().toISOString()}\n\n`;
  return header + stmts.join('\n\n');
}
