import { chromium } from '/tmp/claude-0/-home-user-SchemaForge/9aeaead6-cc50-57d0-9f5b-7b8eeabdf113/scratchpad/pw/node_modules/playwright-core/index.mjs';
import path from 'node:path';
const [page, w, h, name, sel] = process.argv.slice(2);
const dir = new URL('./mockups/', import.meta.url).pathname;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox', '--allow-file-access-from-files'] });
const p = await b.newPage({ viewport: { width: +w, height: +h } });
await p.goto('file://' + path.join(dir, page + '.html')); await p.waitForTimeout(600);
if (sel) await p.locator(sel).first().screenshot({ path: path.join(dir, 'shots', name + '.png') });
else await p.screenshot({ path: path.join(dir, 'shots', name + '.png') });
await b.close();
